name: marp-github-actions
on: [push]
jobs:
  marp-to-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: docker run --rm --init -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli flutter/slide.md --pdf
      - run: docker run --entrypoint sh --rm --init -v $PWD:/home/marp/app/ -e LANG=$LANG marpteam/marp-cli -c "ls -al flutter/"
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: flutter/slide.pdf
